In [31]:
import pandas as pd
import tensorflow as tf

In [2]:
df = pd.read_csv('../data/house-prices.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

### Pré-processamento

In [6]:
colunas_usadas = df.columns[2:-2]
colunas_usadas

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='object')

In [12]:
df = df.loc[:, df.columns.isin(colunas_usadas)]
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

#### Escalonamento

In [16]:
from sklearn.preprocessing import MinMaxScaler # normalização, valores entre 0 e 1

In [22]:
scaler_x = MinMaxScaler()
df[df.columns[1:]] = scaler_x.fit_transform(df[df.columns[1:]])
df.head()

/home/dstrb/anaconda3/envs/tensor/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [24]:
scaler_y = MinMaxScaler()
df[['price']] = scaler_y.fit_transform(df[['price']])
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

#### Classe / Previsores

In [26]:
X = df.drop('price', axis=1)
y = df.price

In [27]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [28]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

#### feature_column

In [33]:
colunas = [ tf.feature_column.numeric_column(key=c) for c in colunas_usadas[1:]]
colunas

[_NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_living', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_lot', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='floors', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='waterfront', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='view', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='condition', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='grade', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_above', shape=(1,), default_value=None, dtype=tf.

#### Split base

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=.3)
X_treinamento.shape, X_teste.shape, y_treinamento.shape, y_teste.shape

((15129, 16), (6484, 16), (15129,), (6484,))

### Treinamento

In [38]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(
    x=X_treinamento,
    y=y_treinamento,
    batch_size=32,
    num_epochs=None,
    shuffle=True
)

In [39]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(
    x=X_treinamento,
    y=y_treinamento,
    batch_size=32,
    num_epochs=10000,
    shuffle=False
)

In [40]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpvsfoyh4p', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc820dd9518>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [41]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpvsfoyh4p/model.ckpt.
INFO:tensorflow:loss = 0.11607784, step = 1
INFO:tensorflow:global_step/sec: 512.49
INFO:tensorflow:loss = 0.015035743, step = 101 (0.196 sec)
INFO:tensorflow:global_step/sec: 611.523
INFO:tensorflow:loss = 0.0042526303, step = 201 (0.164 sec)
INFO:tensorflow:global_step/sec: 618.947
INFO:tensorflow:loss = 0.013768039, step = 301 (0.161 sec)
INFO:tensorflow:global_step/sec: 612.006
INFO:tensorflow:loss = 0.014803703, step = 401 (0.164 

INFO:tensorflow:global_step/sec: 594.372
INFO:tensorflow:loss = 0.014079801, step = 6901 (0.168 sec)
INFO:tensorflow:global_step/sec: 581.802
INFO:tensorflow:loss = 0.013472542, step = 7001 (0.172 sec)
INFO:tensorflow:global_step/sec: 593.688
INFO:tensorflow:loss = 0.033094972, step = 7101 (0.168 sec)
INFO:tensorflow:global_step/sec: 585.048
INFO:tensorflow:loss = 0.017334927, step = 7201 (0.171 sec)
INFO:tensorflow:global_step/sec: 595.4
INFO:tensorflow:loss = 0.02041497, step = 7301 (0.168 sec)
INFO:tensorflow:global_step/sec: 583.199
INFO:tensorflow:loss = 0.018054774, step = 7401 (0.171 sec)
INFO:tensorflow:global_step/sec: 582.254
INFO:tensorflow:loss = 0.061350673, step = 7501 (0.173 sec)
INFO:tensorflow:global_step/sec: 551.253
INFO:tensorflow:loss = 0.01211327, step = 7601 (0.182 sec)
INFO:tensorflow:global_step/sec: 580.402
INFO:tensorflow:loss = 0.01727096, step = 7701 (0.172 sec)
INFO:tensorflow:global_step/sec: 556.851
INFO:tensorflow:loss = 0.013428307, step = 7801 (0.179 

### Métricas

In [42]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-13-01:48:16
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-02-13-01:48:32
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00069948734, global_step = 10000, label/mean = 0.060882542, loss = 0.022383595, prediction/mean = 0.05774878
INFO:tensorflow:Saving 'checkpoint_

In [43]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-13-01:48:47
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-02-13-01:49:03
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00070180313, global_step = 10000, label/mean = 0.06087625, loss = 0.0224577, prediction/mean = 0.057741284
INFO:tensorflow:Saving 'checkpoint_pa

In [44]:
metricas_treinamento

{'average_loss': 0.00069948734,
 'label/mean': 0.060882542,
 'loss': 0.022383595,
 'prediction/mean': 0.05774878,
 'global_step': 10000}

In [45]:
metricas_teste

{'average_loss': 0.00070180313,
 'label/mean': 0.06087625,
 'loss': 0.0224577,
 'prediction/mean': 0.057741284,
 'global_step': 10000}

### Predict

In [47]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(
    x=X_teste, 
    shuffle=False
)

In [51]:
previsoes = [ p['predictions'] for p in regressor.predict(input_fn=funcao_previsao)]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [54]:
previsoes[:5]

[array([0.14760403], dtype=float32),
 array([0.13384227], dtype=float32),
 array([0.15262295], dtype=float32),
 array([-0.00394379], dtype=float32),
 array([0.03570247], dtype=float32)]

### Mean Abs Error

In [59]:
import numpy as np
from sklearn.metrics import mean_absolute_error

In [56]:
valores_previsoes = np.asarray(previsoes).reshape(-1,1)

In [57]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes[:5]

array([[1200480.8  ],
       [1095547.4  ],
       [1238750.   ],
       [  44928.633],
       [ 347231.38 ]], dtype=float32)

In [58]:
y_teste2 = scaler_y.inverse_transform(y_teste.values.reshape(-1,1))
y_teste2[:5]

array([[1200000.],
       [ 995000.],
       [1160000.],
       [ 175000.],
       [ 521500.]])

In [60]:
mean_absolute_error(y_teste2, valores_previsoes)

125861.19651308712