In [1]:
#low level
import tensorflow as tf

In [6]:
p = tf.placeholder('float', None) # None é o shape

In [3]:
op = p + 2

In [5]:
with tf.Session() as sess:
    #print(sess.run(op))
    resultado = sess.run(op, feed_dict={p: [1,2,3]})
    print(resultado)

[3. 4. 5.]


In [12]:
p2 = tf.placeholder('float', (None, 5)) # None é o shape
op2 = p2 * 5

In [14]:
with tf.Session() as sess:
    #print(sess.run(op))
    dados = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
    resultado = sess.run(op2, feed_dict={p2: dados})
    print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
