In [6]:
# low level
import tensorflow as tf

In [10]:
a = tf.constant([9, 8, 7], name='a')
b = tf.constant([1, 2, 3], name='b')

In [3]:
soma = a + b

In [8]:
type(a)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [30]:
m1 = tf.constant([[1, 2, 3], [4, 5, 6]], name='m1')

In [31]:
type(m1)

tensorflow.python.framework.ops.Tensor

In [32]:
m1.shape

TensorShape([Dimension(2), Dimension(3)])

In [33]:
m2 = tf.constant([[1, 2, 3], [4, 5, 6]], name='m2')

In [34]:
soma1 = tf.add(m1,m2)

In [35]:
with tf.Session() as sess:
    print(sess.run(soma1))

[[ 2  4  6]
 [ 8 10 12]]


In [38]:
m2 = tf.constant([[1], [2]], name='m2')
soma1 = tf.add(m1,m2)

In [39]:
with tf.Session() as sess:
    print(sess.run(soma1))

[[2 3 4]
 [6 7 8]]


### Mult. de matrizes

In [40]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[-1, 3], [4, 2]])
mult = tf.matmul(a, b)

In [41]:
with tf.Session() as sess:
    print(sess.run(mult))

[[ 7  7]
 [13 17]]


In [43]:
mult2 = tf.matmul(b, a)
with tf.Session() as sess:
    print(sess.run(mult2))

[[ 8 10]
 [10 16]]
